/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.unicauca.labtrabajogrado.presentation;
import co.unicauca.labtrabajogrado.access.Factory;
import co.unicauca.labtrabajogrado.access.IUserRepositorio;
import co.unicauca.labtrabajogrado.domain.Professor;
import co.unicauca.labtrabajogrado.domain.Student;
import co.unicauca.labtrabajogrado.domain.User;
import co.unicauca.labtrabajogrado.domain.enumPrograma;
import co.unicauca.labtrabajogrado.domain.enumRol;
import co.unicauca.labtrabajogrado.service.Service;
import co.unicauca.labtrabajogrado.utility.EmailValidator;
import co.unicauca.labtrabajogrado.utility.PasswordUtils;
import java.util.Arrays;
import javax.swing.JOptionPane;


/**
 *
 * @author Acer
 */
public class GuiRegister extends javax.swing.JFrame {
    
     private Service service;
      static IUserRepositorio  userRepository;

    /**
     * Creates new form GuiRegister
     */
    public GuiRegister(IUserRepositorio  userRepository) {
        initComponents();
        this.service = new Service(userRepository);
        this.userRepository=userRepository;
        
         comboBoxPrograma.setModel(new javax.swing.DefaultComboBoxModel<>(
        Arrays.stream(enumPrograma.values())
              .map(Enum::name) 
              .toArray(String[]::new)
    ));

    
    comboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(
        Arrays.stream(enumRol.values())
              .map(Enum::name)
              .toArray(String[]::new)
    ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRegistro = new javax.swing.JLabel();
        LabelNombres = new javax.swing.JLabel();
        LabelApellidos = new javax.swing.JLabel();
        LabelPrograma = new javax.swing.JLabel();
        comboBoxPrograma = new javax.swing.JComboBox<>();
        LabelCelular = new javax.swing.JLabel();
        LabelContrasenia = new javax.swing.JLabel();
        comboBoxRol = new javax.swing.JComboBox<>();
        LabelRol = new javax.swing.JLabel();
        LabelEmail = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        txtContrasenia = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtRegistro.setBackground(new java.awt.Color(0, 0, 51));
        txtRegistro.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        txtRegistro.setForeground(new java.awt.Color(102, 102, 255));
        txtRegistro.setText("Registrar Usuario");
        txtRegistro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));

        LabelNombres.setBackground(new java.awt.Color(153, 255, 51));
        LabelNombres.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelNombres.setText("Nombres :");
        LabelNombres.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelApellidos.setBackground(new java.awt.Color(153, 255, 51));
        LabelApellidos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelApellidos.setText("Apellidos :");
        LabelApellidos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelPrograma.setBackground(new java.awt.Color(153, 255, 51));
        LabelPrograma.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelPrograma.setText("Programa :");
        LabelPrograma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        comboBoxPrograma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INGENIERIA_SISTEMAS", "INGENIERIA_ELECTRONICA_TELECOMUNICACIONES", "AUTOMATICA_INDUSTRIAL", "TECNOLOGIA_TELEMATICA" }));
        comboBoxPrograma.setToolTipText("");
        comboBoxPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxProgramaActionPerformed(evt);
            }
        });

        LabelCelular.setBackground(new java.awt.Color(153, 255, 51));
        LabelCelular.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelCelular.setText("Celular :");
        LabelCelular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelContrasenia.setBackground(new java.awt.Color(153, 255, 51));
        LabelContrasenia.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelContrasenia.setText(" Contraseña :");
        LabelContrasenia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        comboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Profesor" }));

        LabelRol.setBackground(new java.awt.Color(153, 255, 51));
        LabelRol.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelRol.setText("Rol :");
        LabelRol.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LabelEmail.setBackground(new java.awt.Color(153, 255, 51));
        LabelEmail.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelEmail.setText("Email :");
        LabelEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnRegistrar.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 51, 153));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(new javax.swing.border.MatteBorder(null));
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnIniciarSesion.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(102, 102, 255));
        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.setBorder(new javax.swing.border.MatteBorder(null));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelCelular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxPrograma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombres)
                            .addComponent(txtApellidos)
                            .addComponent(txtCelular)
                            .addComponent(txtEmail)
                            .addComponent(txtContrasenia)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(txtRegistro))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelRol, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxProgramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxProgramaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
//         try {
//        String nombres = txtNombres.getText();
//        String apellidos = txtApellidos.getText();
//        String celular = txtCelular.getText();
//        String seleccionadoPrograma = comboBoxPrograma.getSelectedItem().toString();
//        enumPrograma programa = enumPrograma.valueOf(seleccionadoPrograma);
//
//        // Convertir String a enumRol
//        String seleccionadoRol = comboBoxRol.getSelectedItem().toString();
//        enumRol rol = enumRol.valueOf(seleccionadoRol);  
//        String email = txtEmail.getText();
//        String contrasenia = new String(txtContrasenia.getPassword());
//
//        User nuevoUsuario = new User(nombres, apellidos, celular, programa, rol, email, contrasenia);
//             JOptionPane.showMessageDialog(this, nuevoUsuario.toString());
//        boolean exito = service.registrarUsuario(nuevoUsuario);
//
//        if (exito) {
//            JOptionPane.showMessageDialog(this, "Usuario registrado con éxito!");
//        } else {
//            JOptionPane.showMessageDialog(this, "Error en el registro. Verifique los datos.");
//        }
//
//    } catch (Exception ex) {
//        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
//    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        GuiLogin login = new GuiLogin(); 
        login.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
                 try {
        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        String celular = txtCelular.getText();
        String seleccionadoPrograma = comboBoxPrograma.getSelectedItem().toString();
        enumPrograma programa = enumPrograma.valueOf(seleccionadoPrograma);

        // Convertir String a enumRol
        String seleccionadoRol = comboBoxRol.getSelectedItem().toString();
        enumRol rol = enumRol.valueOf(seleccionadoRol);  
        String email = txtEmail.getText();
        String contrasenia = new String(txtContrasenia.getPassword());

        User nuevoUsuario = new User(nombres, apellidos, celular, programa, rol, email, contrasenia);
        if (!EmailValidator.esCorreoInstitucional(nuevoUsuario.getEmail())) {
            JOptionPane.showMessageDialog(this, 
                "El dominio del correo debe ser @unicauca.edu.co");
            return; // salir si no cumple
        }

        // Validar contraseña
        if (!PasswordUtils.validarContrasenia(nuevoUsuario.getContraseña())) {
            JOptionPane.showMessageDialog(this, 
                "La contraseña debe cumplir con los siguientes requisitos:\n" +
                "- Al menos 6 caracteres\n" +
                "- Al menos una letra mayúscula\n" +
                "- Al menos un número\n" +
                "- Al menos un carácter especial (@#$%^&+=!¿?.,;:_-)\n" +
                "- No debe contener espacios");
            return; // salir si no cumple
        }

        boolean exito = service.registrarUsuario(nuevoUsuario);

        if (exito) {
            
            JOptionPane.showMessageDialog(this, "Usuario registrado con éxito!");
        } else {
            JOptionPane.showMessageDialog(this, "Error en el registro. Verifique los datos.");
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiRegister(userRepository).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelApellidos;
    private javax.swing.JLabel LabelCelular;
    private javax.swing.JLabel LabelContrasenia;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelNombres;
    private javax.swing.JLabel LabelPrograma;
    private javax.swing.JLabel LabelRol;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> comboBoxPrograma;
    private javax.swing.JComboBox<String> comboBoxRol;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JLabel txtRegistro;
    // End of variables declaration//GEN-END:variables
}
